#!/usr/bin/env bash
#Script that transfers a file from our client to a server

# Check if all parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
# assigning parameters to variables

file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# disabling strict host key checking

scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_path" "$username@$ip:~/"

# cheacking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCESSFULLY"
else
	echo "FILE TRANSFER FAILED"

fi

